/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, clang++ 17.0.0 -fPIC -O3) */

module hamming_decoder(code_in, code_out, error_location, error_flag);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  input [7:0] code_in;
  wire [7:0] code_in;
  output [7:0] code_out;
  wire [7:0] code_out;
  output [1:0] error_flag;
  wire [1:0] error_flag;
  output [2:0] error_location;
  wire [2:0] error_location;
  wire [3:0] syndrome;
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(code_in[3]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _26_ (
    .A(code_in[1]),
    .B(code_in[0]),
    .X(_01_)
  );
  sky130_fd_sc_hd__xor2_1 _27_ (
    .A(code_in[3]),
    .B(code_in[2]),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(code_in[5]),
    .B(code_in[6]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(code_in[4]),
    .B(code_in[6]),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor3_1 _30_ (
    .A(code_in[5]),
    .B(code_in[4]),
    .C(code_in[6]),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor3_1 _31_ (
    .A(_01_),
    .B(_02_),
    .C(_05_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(code_in[7]),
    .B(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _33_ (
    .A(_07_),
    .Y(error_flag[0])
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(code_in[0]),
    .B(code_in[2]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__xor2_1 _35_ (
    .A(_04_),
    .B(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(_04_),
    .B(_08_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_00_),
    .B(_05_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(code_in[3]),
    .B(_05_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(code_in[1]),
    .B(code_in[2]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _40_ (
    .A(_03_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _41_ (
    .A(_11_),
    .B(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_10_),
    .B(_15_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _43_ (
    .A(error_flag[0]),
    .B(_16_),
    .Y(error_flag[1])
  );
  sky130_fd_sc_hd__nor2_1 _44_ (
    .A(_07_),
    .B(_09_),
    .Y(error_location[0])
  );
  sky130_fd_sc_hd__nor2_1 _45_ (
    .A(_07_),
    .B(_14_),
    .Y(error_location[1])
  );
  sky130_fd_sc_hd__nor2_1 _46_ (
    .A(_07_),
    .B(_11_),
    .Y(error_location[2])
  );
  sky130_fd_sc_hd__nor3_1 _47_ (
    .A(_07_),
    .B(_09_),
    .C(_15_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xor2_1 _48_ (
    .A(code_in[0]),
    .B(_17_),
    .X(code_out[0])
  );
  sky130_fd_sc_hd__nor4_1 _49_ (
    .A(_07_),
    .B(_10_),
    .C(_12_),
    .D(_14_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xor2_1 _50_ (
    .A(code_in[1]),
    .B(_18_),
    .X(code_out[1])
  );
  sky130_fd_sc_hd__nor4_1 _51_ (
    .A(_07_),
    .B(_09_),
    .C(_12_),
    .D(_14_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__xor2_1 _52_ (
    .A(code_in[2]),
    .B(_19_),
    .X(code_out[2])
  );
  sky130_fd_sc_hd__nor3b_1 _53_ (
    .A(_07_),
    .B(_10_),
    .C_N(_14_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__mux2i_1 _54_ (
    .A0(_00_),
    .A1(_05_),
    .S(_20_),
    .Y(code_out[3])
  );
  sky130_fd_sc_hd__nand2_1 _55_ (
    .A(_10_),
    .B(_14_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor3_1 _56_ (
    .A(_07_),
    .B(_11_),
    .C(_21_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xor2_1 _57_ (
    .A(code_in[4]),
    .B(_22_),
    .X(code_out[4])
  );
  sky130_fd_sc_hd__nor4_1 _58_ (
    .A(_07_),
    .B(_10_),
    .C(_11_),
    .D(_14_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xor2_1 _59_ (
    .A(code_in[5]),
    .B(_23_),
    .X(code_out[5])
  );
  sky130_fd_sc_hd__nor4_1 _60_ (
    .A(_07_),
    .B(_09_),
    .C(_11_),
    .D(_14_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xor2_1 _61_ (
    .A(code_in[6]),
    .B(_24_),
    .X(code_out[6])
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(code_in[7]),
    .A1(_06_),
    .S(_16_),
    .X(code_out[7])
  );
  assign syndrome[3] = error_flag[0];
endmodule

module hamming_encoder(data_in, code_out);
  wire c0;
  wire c1;
  wire c2;
  wire c_all;
  output [7:0] code_out;
  wire [7:0] code_out;
  input [3:0] data_in;
  wire [3:0] data_in;
  sky130_fd_sc_hd__xor3_1 _0_ (
    .A(data_in[3]),
    .B(data_in[1]),
    .C(data_in[0]),
    .X(code_out[0])
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(data_in[3]),
    .B(data_in[0]),
    .C(data_in[2]),
    .X(code_out[1])
  );
  sky130_fd_sc_hd__xor3_1 _2_ (
    .A(data_in[3]),
    .B(data_in[1]),
    .C(data_in[2]),
    .X(code_out[3])
  );
  sky130_fd_sc_hd__xor3_1 _3_ (
    .A(data_in[1]),
    .B(data_in[0]),
    .C(data_in[2]),
    .X(code_out[7])
  );
  assign c0 = code_out[0];
  assign c1 = code_out[1];
  assign c2 = code_out[3];
  assign c_all = code_out[7];
  assign { code_out[6:4], code_out[2] } = data_in;
endmodule

module tt_um_hamming_top(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _unused;
  input clk;
  wire clk;
  wire [2:0] curr_state;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire [7:0] decoded_data;
  input ena;
  wire ena;
  wire [7:0] encoded_code;
  wire [1:0] errors;
  wire mode_select;
  wire [2:0] next_state;
  input rst_n;
  wire rst_n;
  wire start;
  wire [2:0] syndrome;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  sky130_fd_sc_hd__nor2_1 _059_ (
    .A(curr_state[1]),
    .B(ui_in[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor3b_1 _060_ (
    .A(curr_state[2]),
    .B(curr_state[0]),
    .C_N(curr_state[1]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor3_1 _061_ (
    .A(curr_state[2]),
    .B(curr_state[0]),
    .C(_036_),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__nor2_1 _062_ (
    .A(curr_state[2]),
    .B(curr_state[1]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _063_ (
    .A(curr_state[0]),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2b_1 _064_ (
    .A_N(_037_),
    .B(_039_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__and3b_1 _065_ (
    .A_N(curr_state[2]),
    .B(curr_state[1]),
    .C(curr_state[0]),
    .X(next_state[2])
  );
  sky130_fd_sc_hd__mux2_1 _066_ (
    .A0(ui_in[0]),
    .A1(mode_select),
    .S(_039_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nor3b_1 _067_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C_N(curr_state[2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__or3b_1 _068_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C_N(curr_state[2]),
    .X(_041_)
  );
  sky130_fd_sc_hd__or4b_1 _069_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C(errors[0]),
    .D_N(curr_state[2]),
    .X(_042_)
  );
  sky130_fd_sc_hd__o211ai_1 _070_ (
    .A1(decoded_data[0]),
    .A2(_040_),
    .B1(_042_),
    .C1(mode_select),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(next_state[2]),
    .B(_040_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _072_ (
    .A(next_state[2]),
    .SLEEP(_040_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand2b_1 _073_ (
    .A_N(mode_select),
    .B(encoded_code[0]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor3_1 _074_ (
    .A(data_out[0]),
    .B(next_state[2]),
    .C(_040_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a31oi_1 _075_ (
    .A1(_043_),
    .A2(_045_),
    .A3(_046_),
    .B1(_047_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__or4b_1 _076_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C(errors[1]),
    .D_N(curr_state[2]),
    .X(_048_)
  );
  sky130_fd_sc_hd__o211ai_1 _077_ (
    .A1(decoded_data[1]),
    .A2(_040_),
    .B1(_048_),
    .C1(mode_select),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2b_1 _078_ (
    .A_N(mode_select),
    .B(encoded_code[1]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor3_1 _079_ (
    .A(data_out[1]),
    .B(next_state[2]),
    .C(_040_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a31oi_1 _080_ (
    .A1(_045_),
    .A2(_049_),
    .A3(_050_),
    .B1(_051_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__or4b_1 _081_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C(syndrome[0]),
    .D_N(curr_state[2]),
    .X(_052_)
  );
  sky130_fd_sc_hd__o211ai_1 _082_ (
    .A1(decoded_data[2]),
    .A2(_040_),
    .B1(_052_),
    .C1(mode_select),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2b_1 _083_ (
    .A_N(mode_select),
    .B(encoded_code[2]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor3_1 _084_ (
    .A(data_out[2]),
    .B(next_state[2]),
    .C(_040_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a31oi_1 _085_ (
    .A1(_045_),
    .A2(_053_),
    .A3(_054_),
    .B1(_055_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__or4b_1 _086_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C(syndrome[1]),
    .D_N(curr_state[2]),
    .X(_056_)
  );
  sky130_fd_sc_hd__o211ai_1 _087_ (
    .A1(decoded_data[3]),
    .A2(_040_),
    .B1(_056_),
    .C1(mode_select),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2b_1 _088_ (
    .A_N(mode_select),
    .B(encoded_code[3]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor3_1 _089_ (
    .A(data_out[3]),
    .B(next_state[2]),
    .C(_040_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a31oi_1 _090_ (
    .A1(_045_),
    .A2(_057_),
    .A3(_058_),
    .B1(_017_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__or4b_1 _091_ (
    .A(curr_state[1]),
    .B(curr_state[0]),
    .C(syndrome[2]),
    .D_N(curr_state[2]),
    .X(_018_)
  );
  sky130_fd_sc_hd__o211ai_1 _092_ (
    .A1(decoded_data[4]),
    .A2(_040_),
    .B1(_018_),
    .C1(mode_select),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2b_1 _093_ (
    .A_N(mode_select),
    .B(encoded_code[4]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor3_1 _094_ (
    .A(data_out[4]),
    .B(next_state[2]),
    .C(_040_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a31oi_1 _095_ (
    .A1(_045_),
    .A2(_019_),
    .A3(_020_),
    .B1(_021_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21boi_0 _096_ (
    .A1(decoded_data[5]),
    .A2(_041_),
    .B1_N(mode_select),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o22ai_1 _097_ (
    .A1(mode_select),
    .A2(encoded_code[5]),
    .B1(next_state[2]),
    .B2(_040_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _098_ (
    .A1_N(data_out[5]),
    .A2_N(_044_),
    .B1(_022_),
    .B2(_023_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a21boi_0 _099_ (
    .A1(decoded_data[6]),
    .A2(_041_),
    .B1_N(mode_select),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o22ai_1 _100_ (
    .A1(mode_select),
    .A2(encoded_code[6]),
    .B1(next_state[2]),
    .B2(_040_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _101_ (
    .A1_N(data_out[6]),
    .A2_N(_044_),
    .B1(_024_),
    .B2(_025_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a21boi_0 _102_ (
    .A1(decoded_data[7]),
    .A2(_041_),
    .B1_N(mode_select),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o22ai_1 _103_ (
    .A1(mode_select),
    .A2(encoded_code[7]),
    .B1(next_state[2]),
    .B2(_040_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _104_ (
    .A1_N(data_out[7]),
    .A2_N(_044_),
    .B1(_026_),
    .B2(_027_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(data_in[0]),
    .A1(ui_in[0]),
    .S(_037_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(data_in[1]),
    .A1(ui_in[1]),
    .S(_037_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(data_in[2]),
    .A1(ui_in[2]),
    .S(_037_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(data_in[3]),
    .A1(ui_in[3]),
    .S(_037_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(mode_select),
    .B(ui_in[4]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(data_in[4]),
    .B(_037_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _111_ (
    .A1(_037_),
    .A2(_028_),
    .B1(_029_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(mode_select),
    .B(ui_in[5]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _113_ (
    .A(data_in[5]),
    .B(_037_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _114_ (
    .A1(_037_),
    .A2(_030_),
    .B1(_031_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(mode_select),
    .B(ui_in[6]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(data_in[6]),
    .B(_037_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _117_ (
    .A1(_037_),
    .A2(_032_),
    .B1(_033_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(mode_select),
    .B(ui_in[7]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(data_in[7]),
    .B(_037_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _120_ (
    .A1(_037_),
    .A2(_034_),
    .B1(_035_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(clk),
    .D(_000_),
    .Q(mode_select),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk),
    .D(_001_),
    .Q(data_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk),
    .D(_002_),
    .Q(data_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk),
    .D(_003_),
    .Q(data_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(clk),
    .D(_004_),
    .Q(data_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk),
    .D(_005_),
    .Q(data_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk),
    .D(_006_),
    .Q(data_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(clk),
    .D(_007_),
    .Q(data_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk),
    .D(_008_),
    .Q(data_out[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk),
    .D(_009_),
    .Q(data_in[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk),
    .D(_010_),
    .Q(data_in[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk),
    .D(_011_),
    .Q(data_in[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk),
    .D(_012_),
    .Q(data_in[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk),
    .D(_013_),
    .Q(data_in[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk),
    .D(_014_),
    .Q(data_in[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(clk),
    .D(_015_),
    .Q(data_in[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(clk),
    .D(_016_),
    .Q(data_in[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(curr_state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(curr_state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk),
    .D(next_state[2]),
    .Q(curr_state[2]),
    .RESET_B(rst_n)
  );
  hamming_decoder hamming_decoder_inst (
    .code_in(data_in),
    .code_out(decoded_data),
    .error_flag(errors),
    .error_location(syndrome)
  );
  hamming_encoder hamming_encoder_inst (
    .code_out(encoded_code),
    .data_in(data_in[3:0])
  );
  assign _unused = 1'h0;
  assign start = ui_in[0];
  assign uio_oe = 8'h00;
  assign uio_out = 8'h00;
  assign uo_out = data_out;
endmodule
